// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzhcqiasladwvdvgeyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxemhjcWlhc2xhZHd2ZHZnZXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mzc3MDQsImV4cCI6MjA3NzQxMzcwNH0.LIQUYPjZZoHrZCzv5XDYC3Prxe9UgDEBnNr5X9H90o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});